### ISSUE TITLE
annotater exits with null pointer exception

### ISSUE THREAD

**Issue by cbaakman** [cmbi/whynot#14]
Yesterday, I ran the annotater twice. (master branch, 2.3) In both cases it ended like this:

```
15:44:56,888  INFO Annotater:33 - Annotater start.
15:44:58,355  INFO Converter:133 - Optimizing file /srv/scratch/whynot2/comment/fraud_150818.txt
15:44:58,399  INFO Annotater:84 - Adding annotations in fraud_150818.txt.optimized
15:44:58,399  INFO Annotater:128 - COMMENT: Empty comment: Adding 0 annotations
15:44:59,837  WARN Annotater:108 - Skipping annotation for mmCIF,1g40: No present parent
15:44:59,837  WARN Annotater:108 - Skipping annotation for mmCIF,1g40: No present parent
15:45:01,218  WARN Annotater:108 - Skipping annotation for mmCIF,1g44: No present parent
15:45:01,218  WARN Annotater:108 - Skipping annotation for mmCIF,1g44: No present parent
15:45:02,605  WARN Annotater:108 - Skipping annotation for mmCIF,1l6l: No present parent
15:45:02,605  WARN Annotater:108 - Skipping annotation for mmCIF,1l6l: No present parent
15:45:03,983  WARN Annotater:108 - Skipping annotation for mmCIF,1rid: No present parent
15:45:03,983  WARN Annotater:108 - Skipping annotation for mmCIF,1rid: No present parent
15:45:05,376  WARN Annotater:108 - Skipping annotation for mmCIF,1y8e: No present parent
15:45:05,376  WARN Annotater:108 - Skipping annotation for mmCIF,1y8e: No present parent
15:45:06,741  WARN Annotater:108 - Skipping annotation for mmCIF,2a01: No present parent
15:45:06,741  WARN Annotater:108 - Skipping annotation for mmCIF,2a01: No present parent
15:45:08,117  WARN Annotater:108 - Skipping annotation for mmCIF,2hr0: No present parent
15:45:08,117  WARN Annotater:108 - Skipping annotation for mmCIF,2hr0: No present parent
15:45:09,499  WARN Annotater:108 - Skipping annotation for mmCIF,2ou1: No present parent
15:45:09,499  WARN Annotater:108 - Skipping annotation for mmCIF,2ou1: No present parent
15:45:09,500  INFO Annotater:138 - COMMENT: Structure is fraud: Adding 0 annotations
15:45:09,507  INFO Converter:133 - Optimizing file /srv/scratch/whynot2/comment/wi-list-pdb-150818.txt
15:45:09,511  INFO Annotater:84 - Adding annotations in wi-list-pdb-150818.txt.optimized
15:45:09,511  INFO Annotater:128 - COMMENT: Empty comment: Adding 0 annotations
15:45:24,597  INFO Annotater:128 - COMMENT: Not enough residues: Adding 7 annotations
15:46:40,379  INFO Annotater:138 - COMMENT: Too many residues: Adding 37 annotations
15:46:42,549  INFO Converter:133 - Optimizing file /srv/scratch/whynot2/comment/wi-list-redo-150818.txt
15:46:42,574  INFO Annotater:84 - Adding annotations in wi-list-redo-150818.txt.optimized
15:46:42,574  INFO Annotater:128 - COMMENT: Empty comment: Adding 0 annotations
15:46:49,699  INFO Annotater:128 - COMMENT: Too many C-alpha-only residues: Adding 1 annotations
15:46:51,287  INFO Annotater:128 - COMMENT: Bioinformatics unfriendly aspects: Adding 2 annotations
15:47:05,111  INFO Annotater:128 - COMMENT: Percentage bad residues too high: Adding 2 annotations
15:47:40,374  INFO Annotater:128 - COMMENT: Too many bad residues: Adding 13 annotations
15:49:59,483  INFO Annotater:128 - COMMENT: Too many residues: Adding 91 annotations
15:56:22,793  INFO Annotater:138 - COMMENT: Not enough residues: Adding 253 annotations
15:56:24,906  INFO Converter:133 - Optimizing file /srv/scratch/whynot2/uncomment/scenes-pdb-ss2_20150818.txt
15:56:24,915  INFO Annotater:147 - Removing annotations in scenes-pdb-ss2_20150818.txt.optimized
15:56:24,915  INFO Annotater:197 - COMMENT: Empty comment: Removing 0 annotations
15:56:25,382  WARN Annotater:171 - Skipping annotation for PDB_SCENES_ss2,4r78: Entry not found
15:56:25,382  WARN Annotater:171 - Skipping annotation for PDB_SCENES_ss2,4r78: Entry not found
15:56:25,382  WARN Annotater:171 - Skipping annotation for PDB_SCENES_ss2,4rir: Entry not found
15:56:25,382  WARN Annotater:171 - Skipping annotation for PDB_SCENES_ss2,4rir: Entry not found
15:56:25,383  WARN Annotater:171 - Skipping annotation for PDB_SCENES_ss2,4tkd: Entry not found
15:56:25,383  WARN Annotater:171 - Skipping annotation for PDB_SCENES_ss2,4tkd: Entry not found
15:56:25,383  WARN Annotater:171 - Skipping annotation for PDB_SCENES_ss2,4wig: Entry not found
15:56:25,383  WARN Annotater:171 - Skipping annotation for PDB_SCENES_ss2,4wig: Entry not found
15:56:25,383  WARN Annotater:171 - Skipping annotation for PDB_SCENES_ss2,4wtp: Entry not found
15:56:25,383  WARN Annotater:171 - Skipping annotation for PDB_SCENES_ss2,4wtp: Entry not found
15:56:25,383  WARN Annotater:171 - Skipping annotation for PDB_SCENES_ss2,4wtr: Entry not found
15:56:25,383  WARN Annotater:171 - Skipping annotation for PDB_SCENES_ss2,4wtr: Entry not found
15:56:25,383  WARN Annotater:171 - Skipping annotation for PDB_SCENES_ss2,4wts: Entry not found
15:56:25,383  WARN Annotater:171 - Skipping annotation for PDB_SCENES_ss2,4wts: Entry not found
15:56:25,383  WARN Annotater:171 - Skipping annotation for PDB_SCENES_ss2,4z5q: Entry not found
15:56:25,383  WARN Annotater:171 - Skipping annotation for PDB_SCENES_ss2,4z5q: Entry not found
15:56:25,383  WARN Annotater:171 - Skipping annotation for PDB_SCENES_ss2,5ccj: Entry not found
15:56:25,383  WARN Annotater:171 - Skipping annotation for PDB_SCENES_ss2,5ccj: Entry not found
15:56:25,383  WARN Annotater:171 - Skipping annotation for PDB_SCENES_ss2,5cvi: Entry not found
15:56:25,383  WARN Annotater:171 - Skipping annotation for PDB_SCENES_ss2,5cvi: Entry not found
15:56:25,383  WARN Annotater:171 - Skipping annotation for PDB_SCENES_ss2,5cwa: Entry not found
15:56:25,383  WARN Annotater:171 - Skipping annotation for PDB_SCENES_ss2,5cwa: Entry not found
15:56:25,383  WARN Annotater:171 - Skipping annotation for PDB_SCENES_ss2,5czg: Entry not found
15:56:25,383  WARN Annotater:171 - Skipping annotation for PDB_SCENES_ss2,5czg: Entry not found
15:56:25,383  WARN Annotater:171 - Skipping annotation for PDB_SCENES_ss2,5d1j: Entry not found
15:56:25,383  WARN Annotater:171 - Skipping annotation for PDB_SCENES_ss2,5d1j: Entry not found
15:56:25,384  INFO Annotater:216 - COMMENT: Error creating YASARA scene: Removing 0 annotations
15:56:25,560  INFO Converter:133 - Optimizing file /srv/scratch/whynot2/uncomment/scenes-redo-ss2_20150818.txt
15:56:25,614  INFO Annotater:147 - Removing annotations in scenes-redo-ss2_20150818.txt.optimized
15:56:25,615  INFO Annotater:197 - COMMENT: Empty comment: Removing 0 annotations
15:56:25,955  WARN Annotater:171 - Skipping annotation for REDO_SCENES_ss2,4wtp: Entry not found
15:56:25,955  WARN Annotater:171 - Skipping annotation for REDO_SCENES_ss2,4wtp: Entry not found
15:56:25,955  INFO Annotater:216 - COMMENT: Error creating YASARA scene: Removing 0 annotations
15:56:25,961  INFO Converter:133 - Optimizing file /srv/scratch/whynot2/uncomment/scenes-pdb-iod_20150818.txt
15:56:25,982  INFO Annotater:147 - Removing annotations in scenes-pdb-iod_20150818.txt.optimized
15:56:25,983  INFO Annotater:197 - COMMENT: Empty comment: Removing 0 annotations
15:56:26,042  WARN Annotater:171 - Skipping annotation for PDB_SCENES_iod,5c5p: Entry not found
15:56:26,042  WARN Annotater:171 - Skipping annotation for PDB_SCENES_iod,5c5p: Entry not found
15:56:26,042  WARN Annotater:171 - Skipping annotation for PDB_SCENES_iod,5cv7: Entry not found
15:56:26,042  WARN Annotater:171 - Skipping annotation for PDB_SCENES_iod,5cv7: Entry not found
15:56:26,042  WARN Annotater:171 - Skipping annotation for PDB_SCENES_iod,5cv8: Entry not found
15:56:26,042  WARN Annotater:171 - Skipping annotation for PDB_SCENES_iod,5cv8: Entry not found
15:56:26,042  INFO Annotater:216 - COMMENT: Error creating YASARA scene: Removing 0 annotations
15:56:26,164 ERROR Annotater:60 - File uncomment/wi-list-redo-iod_20150722.txt is empty and should probably be removed: Skipping it for now.. 
15:56:26,164 ERROR Annotater:60 - File uncomment/wi-list-redo-iod_20150722.txt is empty and should probably be removed: Skipping it for now.. 
15:56:39,615  WARN LoadContexts:132 - fail-safe cleanup (collections) : org.hibernate.engine.loading.CollectionLoadContext@5b79b2c6<rs=com.mchange.v2.c3p0.impl.NewProxyResultSet@7acfb741>
15:56:39,615  WARN LoadContexts:132 - fail-safe cleanup (collections) : org.hibernate.engine.loading.CollectionLoadContext@5b79b2c6<rs=com.mchange.v2.c3p0.impl.NewProxyResultSet@7acfb741>
Exception in thread "main" java.lang.NullPointerException
        at java.lang.String.compareTo(String.java:1139)
        at nl.ru.cmbi.whynot.model.Databank.compareTo(Databank.java:102)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:197)
        at nl.ru.cmbi.whynot.model.Databank_$$_javassist_1.compareTo(Databank_$$_javassist_1.java)
        at nl.ru.cmbi.whynot.model.Entry.compareTo(Entry.java:65)
        at nl.ru.cmbi.whynot.model.Annotation.compareTo(Annotation.java:54)
        at nl.ru.cmbi.whynot.model.Annotation.compareTo(Annotation.java:17)
        at java.util.TreeMap.compare(TreeMap.java:1188)
        at java.util.TreeMap.put(TreeMap.java:531)
        at java.util.TreeSet.add(TreeSet.java:255)
        at java.util.AbstractCollection.addAll(AbstractCollection.java:342)
        at java.util.TreeSet.addAll(TreeSet.java:312)
        at org.hibernate.collection.PersistentSet.endRead(PersistentSet.java:352)
        at org.hibernate.engine.loading.CollectionLoadContext.endLoadingCollection(CollectionLoadContext.java:261)
        at org.hibernate.engine.loading.CollectionLoadContext.endLoadingCollections(CollectionLoadContext.java:246)
        at org.hibernate.engine.loading.CollectionLoadContext.endLoadingCollections(CollectionLoadContext.java:219)
        at org.hibernate.loader.Loader.endCollectionLoad(Loader.java:1005)
        at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:993)
        at org.hibernate.loader.Loader.doQuery(Loader.java:857)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:274)
        at org.hibernate.loader.Loader.loadCollection(Loader.java:2166)
        at org.hibernate.loader.collection.CollectionLoader.initialize(CollectionLoader.java:62)
        at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:627)
        at org.hibernate.event.def.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:83)
        at org.hibernate.impl.SessionImpl.initializeCollection(SessionImpl.java:1863)
        at org.hibernate.collection.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:369)
        at org.hibernate.collection.AbstractPersistentCollection.read(AbstractPersistentCollection.java:111)
        at org.hibernate.collection.AbstractPersistentCollection.readSize(AbstractPersistentCollection.java:134)
        at org.hibernate.collection.PersistentSet.isEmpty(PersistentSet.java:169)
        at nl.ru.cmbi.whynot.annotate.Annotater.removeUnusedComments(Annotater.java:228)
        at nl.ru.cmbi.whynot.annotate.Annotater$$FastClassByCGLIB$$f5d09685.invoke(<generated>)
        at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:689)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622)
        at nl.ru.cmbi.whynot.annotate.Annotater$$EnhancerByCGLIB$$1e1627a1.removeUnusedComments(<generated>)
        at nl.ru.cmbi.whynot.annotate.Annotater.main(Annotater.java:64)
Command exited with non-zero status 1

```

My suspicion is that is occurs here:
https://github.com/cmbi/whynot/blob/master/whynot-core/src/main/java/nl/ru/cmbi/whynot/model/Databank.java#L102

It's odd, since the databank.name and entry.databank_id fields have been configured NOT NULL in psql.

**Comment by jonblack** [comment]
This issue is based on the java version of whynot which no longer exists.
