### ISSUE TITLE
Crawl failing

### ISSUE THREAD

**Issue by cbaakman** [cmbi/whynot#42]
The script crawl.py on chelonium fails to update the whynot mongo database. Presumably the port number has changed and the mongo database runs in a docker container now.

**Comment by jonblack** [comment]
Why do you think it's failing?

**Comment by cbaakman** [comment]
Running the following command: ``` /srv/data/scratch/whynot2/crawl.py NMR /srv/data/nmr_restraints/ ```

Results in the following error:
```
Traceback (most recent call last):
  File "/srv/data/scratch/whynot2/crawl.py", line 11, in <module>
    storage.authenticate ('whynotadmin', 'waivuy8N')
  File "/srv/data/scratch/whynot2/storage.py", line 59, in authenticate
    self._db.authenticate (username, passwd)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/database.py", line 988, in authenticate
    connect=True)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 392, in _cache_credentials
    writable_preferred_server_selector)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 121, in select_server
    address))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 97, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: chelonium.cmbi.umcn.nl:27017: [Errno 111] Connection refused
```

**Comment by jonblack** [comment]
The crawler and annotator are now run inside the application in docker. They no longer need to be managed on the server. If you're running a cron job for this, you can remove it. The mongo database is also in a container.
