### ISSUE TITLE
Exception: no such databank: PDB_REDO

### ISSUE THREAD

**Issue by jonblack** [cmbi/whynot#47]
The following error appears in the logs:

```
[2016-12-01 07:06:54,761] ERROR in app: Exception on /resources/list/PDB_REDO_UNANNOTATED/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/whynot/frontend/routes.py", line 137, in resources
    for entry in get_entries_from_collection(databank_name, collection):
  File "/usr/src/app/utils.py", line 196, in get_entries_from_collection
    return get_unannotated_entries(databank_name)
  File "/usr/src/app/utils.py", line 400, in get_unannotated_entries
    for entry in get_missing_entries(databank_name):
  File "/usr/src/app/utils.py", line 366, in get_missing_entries
    raise Exception("no such databank: " + databank_name)
Exception: no such databank: PDB_REDO
```

**Comment by jonblack** [comment]
@cbaakman, @drlemmus
This is caused by the `/resources/list` endpoint, but as far as I can tell this isn't included in a template, which means it's being called from a script/manually. It returns a text file with pdb ids for the given databank and collection. Do either of you know where/why it's used?

**Comment by drlemmus** [comment]
This is used by the PDB to get a list of entries for PDB_REDO.

**Comment by jonblack** [comment]
Closed it by mistake.

What's the PDB in this case? You mean pdb.org or our own databank scripts?

**Comment by drlemmus** [comment]
PDBe and RCSB and possibly others use it to put links on their sites.
